try:
    raise
except:
    print 'exception1'
